name: Deploy using SSH

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment:
      name: production
    steps:
      - name: ssh
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key	: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: cd ${{ secrets.SSH_PROJECT_DIR }} && git pull && npm install && npx tsc && pm2 restart line-notify-utokyo-zenki
