name: Deploy using SSH

on:
  push:
    branches:
      - main
      - staging

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: 
      name: ${{ github.ref == 'refs/heads/main' && 'production' || 'staging' }}
    steps:
      - name: info
        run: |
          echo "Deploying to ${{ github.ref == 'refs/heads/main' && 'production' || 'staging' }} environment"
          echo "Build number: ${{ github.run_number }}"
      - name: ssh
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key	: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: cd ${{ secrets.SSH_PROJECT_DIR }} && git reset --hard && git pull && npm install && npx prisma migrate deploy && npx prisma generate && npx tsc && pm2 restart ecosystem.config.js ${{ github.ref == 'refs/heads/staging' && '--env staging' || '' }}
